[_]
schema-version = "0.2"
id = "com.orange-cloudfoundry.sample-apps.mysql"
name = "MySQL sample app"
#version = "1.0.0"

[io.buildpacks]
builder = "paketobuildpacks/builder-jammy-full"
#include = [
#    "assets/sinatra_app"
#]
